server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_database
    driver-class-name: org.postgresql.Driver
    username: tech_lead
    password: tech_lead
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  kafka:
    bootstrap-servers: localhost:9092,localhost:29092
